# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = SharedLibrary
DESTDIR = ../x64/Debug
CONFIG += debug
DEFINES += $(Qt_DEFINES_) %(PreprocessorDefinitions)SHARED_LIBRARY_EXPORT $(NOINHERIT)
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(SharedLibrary.pri)
