# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./MainWindow/MainWindow.h \
    ./WidgetUI/ToolBar/ToolBar.h \
    ./WidgetUI/CentralWidget/CentralWidget.h \
    ./WidgetUI/CentralWidget/PluginDataWidget.h \
    ./WidgetManage/ToolBarManage.h \
    ./WidgetManage/ToolTipManage.h \
    ./WidgetUI/CentralWidget/WidgetShowWidget.h \
    ./WidgetUI/SidebarWidget/SidebarWidget.h \
    ./WidgetUI/SidebarWidget/TitleBarWidget.h \
    ./WidgetManage/CentralWidgetManage.h \
    ./WidgetManage/SidebarWidgetManage.h \
    ./WidgetUI/ToolBar/SetupDialog.h \
    ./WidgetUI/ToolBar/MatchDialog.h \
    ./WidgetUI/ToolBar/OpenDialog.h
SOURCES += ./MainWindow/MainWindow.cpp \
    ./WidgetManage/CentralWidgetManage.cpp \
    ./WidgetManage/SidebarWidgetManage.cpp \
    ./WidgetManage/ToolBarManage.cpp \
    ./WidgetManage/ToolTipManage.cpp \
    ./WidgetUI/CentralWidget/CentralWidget.cpp \
    ./WidgetUI/SidebarWidget/TitleBarWidget.cpp \
    ./WidgetUI/ToolBar/MatchDialog.cpp \
    ./WidgetUI/ToolBar/OpenDialog.cpp \
    ./WidgetUI/CentralWidget/PluginDataWidget.cpp \
    ./WidgetUI/SidebarWidget/SidebarWidget.cpp \
    ./WidgetUI/ToolBar/SetupDialog.cpp \
    ./WidgetUI/ToolBar/ToolBar.cpp \
    ./WidgetUI/CentralWidget/WidgetShowWidget.cpp \
    ./main.cpp
FORMS += ./MainWindow/MainWindow.ui \
    ./WidgetUI/ToolBar/MatchDialog.ui \
    ./WidgetUI/ToolBar/OpenDialog.ui \
    ./WidgetUI/ToolBar/SetupDialog.ui
RESOURCES += ToolGui.qrc
