# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ToolGui
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"." \
    -lcomponents \
    -lSharedLibrary
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(ToolGui.pri)
